version: '3.1'

services:
  database:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --skip-innodb-read-only-compresse --skip-innodb-read-only-compressed
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=gipcat
      - MYSQL_DATABASE=gipcat
      - MYSQL_USER=gipcat
    ports:
      - 10.8.0.10:3306:3306

  backend:
    image: vittodevit/gipcat:live
    restart: always
    environment:
      - ORIGIN=https://gc.cusenzaservice.it
      - USER=gipcat
      - DB=gipcat
      - PASSWORD=gipcat
      - HOST=database
    ports:
      - 10.8.0.10:8080:8080