# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker image [LIVE]

on:
  push:
    branches: ['main']

jobs:
  push_to_registries:
    name: Push Docker image to DockerHub and ghcr.io
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: |
            vittodevit/gipcat
            ghcr.io/${{ github.repository }}
      
      - name: Build and push Docker images
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: vittodevit/gipcat:live
          labels: ${{ steps.meta.outputs.labels }}


  update_server_img:
    name: Trigger image refresh on prod server
    needs: push_to_registries
    runs-on: ubuntu-18.04
    steps:
      - name: Set Variables
        uses: allenevans/set-env@v2.0.0
        with:
          OVPN: ${{ secrets.OVPN }}

      - name: Write VPN Files
        run: |
          mkdir ~/.ssh
          echo "$OVPN" > ~/.ssh/vpn.ovpn

      - name: Install OpenVPN
        run: |
          sudo apt install apt-transport-https
          sudo wget https://swupdate.openvpn.net/repos/openvpn-repo-pkg-key.pub
          sudo apt-key add openvpn-repo-pkg-key.pub
          sudo wget -O /etc/apt/sources.list.d/openvpn3.list https://swupdate.openvpn.net/community/openvpn3/repos/openvpn3-bionic.list
          sudo apt update
          sudo apt install openvpn3

      - name: Start OpenVPN
        run: openvpn3 session-start --config ~/.ssh/vpn.ovpn
      
      - name: Execute remote update commands
        uses: appleboy/ssh-action@master
        with:
          host: 10.8.0.1
          username: centos
          key: ${{ secrets.SSH_PPK }}
          port: 22
          script: |
            cd /home/centos/gipcat-be
            ls -al
